title: #Jim Steele # your name (or website title) here
logo: #"/images/jimBanff\ small.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer on the Edge
  <br><br>
  #Machine Learning 
  <br><br>
 # <a href="https://www.linkedin.com/in/dijieming/">LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-K3V67WG1GE # your Google Analytics tracking ID here
